### ISSUE TITLE
Blank alignment key

### ISSUE THREAD

**Issue by lishen** [shenlab-sinai/NGS-Data-Charmer#4]
https://github.com/shenlab-sinai/NGS-Data-Charmer/blob/e91e49e87aac92e216ed2a94569931de9113f9a3/config.yaml#L5

Does the pipeline support only one aligner at the moment? What is this `alignment` key suppose to do? Better be explicit than implicit.

**Comment by aartrama** [comment]
The pipeline supports only HISAT2 at the moment. Will be adding support for more aligners soon. `alignment` key changed to `threads_for_alignment`.
